New sqs, new ranking column working, fixed bug regarding convert_t()

diff --git a/sqs b/sqs
--- a/sqs
+++ b/sqs
@@ -11,7 +11,7 @@
 # 									    #
 # This script assumes squeue, sinfo and scontrol are in the default path    #
 # 									    #
-# Version: 1.3								    #
+# Version: 2.0								    #
 #***************************************************************************#
 
 # Some initial setup
@@ -19,7 +19,7 @@
 export PATH=/opt/slurm/default/bin:$PATH
 LC_ALL=C
 
-if [ -n "${NERSC_HOST+1}" ]; then
+if [ -n "$NERSC_HOST" ]; then
 	c_host=$NERSC_HOST
 else
 	c_host=$(hostname)
@@ -37,7 +37,6 @@ then
 	myuser=$(whoami)
 elif  logname &>/dev/null
 then
-
 	myuser=$(logname)
 fi
 sqs=$(basename -- "$0")
@@ -46,12 +45,21 @@ sqs=$(basename -- "$0")
 ## 1
 set -o pipefail
 
+squeueargs=()
+userr=0
+w_header="JOBID              ST   USER       NAME         NODES REQUESTED  USED       SUBMIT_TIME           PARTITION  QOS        MEMORY     CPUS       REPO       RANK_P   RANK_BF  REASON"
+c_header="JOBID              ST   REASON       USER         NAME         NODES        USED         REQUESTED    SUBMIT                PARTITION    RANK_P       RANK_ST"
+
+### BEGIN OF FUNCTIONS SECTION ###
+
 border() {
+# Pretty borders for sqs -s
 printf '=%.0s' {1..70}
 echo
 }
 
 validate() {
+# Validate availability of SLURM tools
 if ! type -P "$1" &>/dev/null; then
 	echo "$sqs: Fatal error - $1 not found."
 	exit 1
@@ -65,11 +73,6 @@ echo "$sqs: Unrecognized option $1" >&2
 exit 1
 }
 
-squeueargs=()
-userr=0
-w_header="JOBID              ST   USER       NAME         NODES REQUESTED  USED       SUBMIT_TIME           PARTITION  QOS        MEMORY     CPUS       REPO       RANK_P   RANK_BF  REASON"
-c_header="JOBID              ST   REASON     USER     NAME         NODES USED     REQUESTED  SUBMIT                PARTITION  RANK_P  RANK_ST"
-
 synopsis() {
 
 echo "usage
@@ -82,22 +85,17 @@ echo "usage
 
         -s Prints a summary about jobs in the queue
 
-        -p partition [partition,partition...] Print jobs in the partition(s) specified
+        -p partition[,partition,partition...] Print jobs in the partition(s) specified
 
-	-np partition [partition,partition...] Do not print jobs in the partition(s) specified
+	-np partition[,partition,partition...] Do not print jobs in the partition(s) specified
 
         -n Displays formatted information about partitions and nodes
 
-        -f jobid Prints very detailed information about jobid or all jobs if no jobid provided.
+        -f jobid[,jobid,jobid...] Prints very detailed information about jobid or all jobs if no jobid provided.
 
 	-x Wide listing including array expanded jobs
 
-	-p partition Displays only jobs in given partition.
-
-        --help Prints synopsis
-	
-	jobid or jobid jobid... Prints only specified jobs, can be either a single job or a list of jobids separated by whitespace"
-
+        --help Prints usage"
 
 	exit "$1"
 }
@@ -109,17 +107,7 @@ squeue "${squeueargs[@]}"
 
 convert_t() {
 # Convert REQUESTED TIME timestamps. e.g.: 1-00:00:00 to 24:00:00
-awk '{n=split($'$1',a,"[-:]");if(n=="4")a[1]=a[1]*24+a[2];if(n=="4")$'$1' = sprintf("%s:%s:%s", a[1], a[2], a[3]);print}'
-}
-
-assort_rank() {
-# Custom, prettier sort: RUNNING JOBS > PD JOBS > OTHER
-if [ $1 == "0" ]
-then
-	awk '{ if ($2 == "R") r = r ORS $0; else if ($2 == "PD" && $11 ~ /[0-9]/) rr = rr ORS $0; else if ($2 == "PD" && $11 == " ") na = na ORS $0; else restt = restt ORS $0; next } { printf "%s", $0 } END { print r rr na restt }'
-else
-	awk '{ if ($2 == "R") r = r ORS $0; else if ($2 == "PD" && $10 ~ /[0-9]/) rr = rr ORS $0; else if ($2 == "PD" && $10 == " ") na = na ORS $0; else restt = restt ORS $0; next } { printf "%s", $0 } END { print r rr na restt }'
-fi
+awk '{n=split($'$1',a,"[-:]");if(n=="4")a[1]=a[1]*24+a[2];if(n=="4")$'$1' = sprintf("%s:%s:%s", a[1], a[3], a[4]);print}'
 }
 
 res=$(mktemp /tmp/XXXXXX || exit 1)
@@ -177,29 +165,19 @@ awk '{ if ($2 == "R") r = r ORS $0; else if ($2 == "PD" && $3 == "Resources") rr
 }
 
 arrange() {
-# sorts starttime column while preserving the header.
+# sorts starttime column
 if (( "$1" == "0" )); then
-	sort -b -k11,11
+	sort -b -k11
 elif (( "$1" == "1" )); then
 	sort -b -k12
 fi
 }
 
-remove_col() {
-# Goes with compact format (Removes column 13 after ranking is properly set. * column RANK needs column 13 and 3)
-awk '{for(i=1;i<=NF;i++) line=(i==1)?$i:((i==13)?line:line OFS $i);print line}'
-}
-
-qos_slicer() {
-# Clean up QOS rows
-awk '{gsub(/low.*/,"low",$11)}{print}' | awk '{gsub("killab","killable",$11)}{print}' | awk '{gsub("premiu","premium",$11)}{print}' | awk '{gsub("scaven","scavenger",$11)}{print}' | awk '{gsub("serial","serialize",$11)}{print}' | awk '{gsub(/part_.*/,"part",$11)}{print}'
-}
-
 rearrange() {
-# Fix the format style
+# Fix the formatting
 n_format=$1
 if [[ "$n_format" == "1" ]]; then
-	awk '{printf "%-18s %-4s %-10s %-8s %-12s %-5s %-8s %-10s %-21s %-10s %-8s %-5s\n", $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$14,$13 ; }'
+	awk '{printf "%-18s %-4s %-12s %-12s %-12s %-12s %-12s %-12s %-21s %-12s %-12s %-12s\n", $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$14,$13 ; }'
 	#awk '{printf "%-18s %-4s %-10s %-14s %-15s %-15s %-12s %-10s %-21s %-10s %-15s %-15s\n", $1,$2,$4,$5,$6,$7,$8,$9,$10,$18,$17,$13,$14 ; }'
 fi
 if [[ "$n_format" == "2" ]]; then
@@ -208,7 +186,9 @@ if [[ "$n_format" == "2" ]]; then
 #sed -e "1 s/^.*$/$wide_header/"
 fi
 }
+
 chop() {
+# -np && -p function, chops partitions according to user flags
 if [[ -n "$1" && ! -n "$2" ]]
 then
 	awk '{print}' > $mytemp
@@ -396,7 +376,7 @@ exit 0
 # sqs with no args
 if (( $# == "0" )); then
 	echo "$c_header"
-        squeue -o "%.18i %.2t %.10r %.10u %.12j %.5D %.5M %.10l %.20V %.12P %.20S %.15Q" | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1 | convert_t 7 | grep -w "$myuser"
+        squeue -h -o "%.18i %.2t %.10r %.10u %.12j %.5D %.5M %.10l %.20V %.12P %.20S %.15Q" | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1
         exit 0
 fi
 
@@ -412,23 +392,15 @@ formatonce() {
 	fi
 }
 
-# want to do something with this
+### END OF FUNCTIONS SECTION ###
 
-function arghandler {
-	if [[ $2 -gt "$1" ]]; then
-	synopsis 1
-	fi
-}
-
-# parsing flags
+# parsing flags/options
 thenp=1
 parts=1
-dasha=1
 while true; do
         case $1 in
+
                 -w)
-			dasha=0
-			userr=1
                         format="2"
 			name="$USER"
                         shift
@@ -441,7 +413,7 @@ while true; do
 		-p)
 			a_parts=$(mktemp)
 			sinfo -O partition > $a_parts
-			if [ -n $2 ];
+			if [ -n "$2" ];
 			then
 				IFS=, read -ra part <<< "$2"; for i in "${part[@]}"
 				do
@@ -459,12 +431,11 @@ while true; do
 			grab_p="$2"
 			parts=0			
 			shift 2
-			#shift
 			;;
 		-np)
 			np_parts=$(mktemp)
 			sinfo -O partition > $np_parts
-			if [ -n $2 ];
+			if [ -n "$2" ];
 			then
 				IFS=, read -ra partv <<< "$2"; for v in "${partv[@]}"
 				do
@@ -493,22 +464,15 @@ while true; do
 				summary
 			fi
 			;;
-		-a)
-			dasha="0"
-			userr=0
-			shift
-			;;
                 -u)
                         shift
 			case $1 in
 				[a-zA-Z]*)
-					dasha="0"
 					userr="1"
                         		name="$1"
 					shift
 					;;
 				*)
-					dasha="0"
 					userr="1"
 					name="$USER"
 					;;
@@ -531,7 +495,6 @@ while true; do
 			shift
 			        if [ $# == 0 ];then sinfo -o "%.10P %.10a %.15l %.20F";fi
 			        if [ $sum ];then summary;fi
-				# if there is no more args then exit
 				(( ! $# )) && exit 0
 			case $1 in
 				-s)
@@ -559,29 +522,35 @@ while true; do
 					;;
 			esac
 			;;
+		-j)
+			if [ -n "$2" ]; then
+				re='^[0-9]+$'	
+				IFS=, read -ra myjids <<< "$2"; for i in "${myjids[@]}"
+				do
+					if [[ "$i" =~ $re ]]; then
+						continue
+					else
+						echo "$sqs: Aborting, $i not a number."
+						exit 1
+					fi
+				done
+			fi
+			jids=$(echo "$2" | tr ',' '|')
+			shift 2
+			;;
                 -*)
 			opterr "$1"
                         ;;
 		[a-zA-Z]*)
 			opterr "$1"
 			;;
-		#["@#$%^*()-_=+"]*)
-		#	opterr "$1"
-		#	;;
-		!*)
-                        opterr "$1"
-			;;
-	        ?*)
-                        opterr "$1"
-			;;
                 *)
 			break
                         ;;
         esac
 done
-# run
+# Put everything together and run
 formatonce
-dasha
 if [[ "$format" == 2 && "$parts" != 0 ]]
 then
 		if [[ "$userr" == 1 ]]
@@ -592,7 +561,7 @@ then
 			exit 0
 		else
 			echo "$w_header"
-			cat f1 | convert_t 7 | rank_resources 1 | arrange 1 | adjust "1" | adj 1 | resources | rearrange 2 
+			cmd | convert_t 7 | rank_resources 1 | arrange 1 | adjust "1" | adj 1 | resources | rearrange 2 
 			if [ $sum ];then summary;fi
 			exit 0
 		fi
@@ -615,12 +584,12 @@ elif [[ "$format" == 1 && "$parts" != 0 ]]; then
 		if [[ "$userr" == 1 ]]
 		then
 			echo "$c_header"
-			cmd | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1 | convert_t 7 | grep -w "$name"
+			cmd | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1 | grep -w "$name"
 			if [ $sum ];then summary;fi
 			exit 0
 		else
 			echo "$c_header"
-			cat f2 | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1
+			cmd | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1
 			if [ $sum ]; then summary;fi
 			exit 0
 		fi
@@ -628,12 +597,12 @@ elif [[ "$format" == 1 && "$parts" == 0 ]]; then
 		if [[ "$userr" = 1 ]]
 		then
 			echo "$c_header"
-			cmd | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1 | convert_t 7 | grep -w "$name" | chop "$grab_p" "$nps"
+			cmd | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1 | grep -w "$name" | chop "$grab_p" "$nps"
 			if [ $sum ]; then summary;fi
 			exit 0
 		else
 			echo "$c_header"
-			cmd | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1 | convert_t 7 | chop "$grab_p" "$nps"
+			cmd | convert_t 8 | rank_resources 0 | arrange 0 | adjust 0 | adj 0 |resources | rearrange 1 | chop "$grab_p" "$nps"
                         if [ $sum ]; then summary;fi
                         exit 0
                 fi
